Lab2_SWT/Controllers/ADMINController.cs
using LMMProject.Data;
using LMMProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LMMProject.Controllers
{
    public class ADMINController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IHttpContextAccessor _Accessor;
        public ADMINController(AppDbContext context, IHttpContextAccessor accessor)
        {
            _context = context;
            _Accessor = accessor;
        }
        public IActionResult Dashboard()
        {
            return View();
        }

        public IActionResult Infor()
        {
            string userName=_Accessor.HttpContext.Session.GetString("Username");
            var Account = _context.Account.Include(p => p.Role).FirstOrDefault(pro => pro.UserName.Equals(userName));
            return View(Account);
        }
        [HttpPost]
        public async Task<IActionResult> Infor(Account account)
        {
            var accountChange = new Account();
            accountChange = _context.Account.Include(p => p.Role).FirstOrDefault(pro => pro.UserName.Equals(account.UserName));
            accountChange.UserName=account.UserName;
            accountChange.Fullname=account.Fullname;
            accountChange.Address=account.Address;
            accountChange.Phone=account.Phone;
            accountChange.Gender=account.Gender;
            accountChange.Birthday=account.Birthday;
           _context.Account.Update(accountChange);
           _context.SaveChanges();
            return RedirectToAction("Infor");
        }

        public IActionResult ListOfCurriculum()
        {
            var listCurriculum = _context.Curriculum.Include(p => p.Decision).ToList();
            return View(listCurriculum);
        }
        public IActionResult ListOfCombo()
        {
            var listCombo = _context.Combo.Include(a => a.Curriculum).ToList();
            return View(listCombo);
        }
        public IActionResult ComboSubject()
        {
            var ComboSubject = _context.Combo_Subject.Include(a => a.Subject).Include(p=> p.Combo).ToList();
            return View(ComboSubject); 
        }

    }
}

Lab2_SWT/Controllers/ADMINMaterialOfTeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMMProject.Data;
using LMMProject.Models;

namespace LMMProject.Controllers
{
    public class ADMINMaterialOfTeacherController : Controller
    {
        private int count_Index;
        private readonly AppDbContext _context;

        public ADMINMaterialOfTeacherController(AppDbContext context)
        {
            _context = context;
        }

        // GET: ADMINMaterialOfTeacher
        public async Task<IActionResult> Index(string status, string sub_code)
        {
            
            List<MaterialOfTeacher> list =  await _context.MaterialOfTeacher.Include(m => m.Account).Include(m => m.Subject).ToListAsync();
            
                if (!string.IsNullOrEmpty(status))
                {
                if (!status.Equals("") && !status.Equals("all"))
                {
                    if (!string.IsNullOrEmpty(sub_code))
                    {
                        list = await _context.MaterialOfTeacher.Include(m => m.Account).Include(m => m.Subject).Where(m => m.Status.Equals(status)).Where(m => m.SubjectCode.Contains(sub_code)).ToListAsync();
                    }
                    else
                    {
                        list = await _context.MaterialOfTeacher.Include(m => m.Account).Include(m => m.Subject).Where(m => m.Status.Equals(status)).ToListAsync();
                    }
                }
                else
                {
                    if (!string.IsNullOrEmpty(sub_code))
                    {
                        list = await _context.MaterialOfTeacher.Include(m => m.Account).Include(m => m.Subject).Where(m => m.SubjectCode.Contains(sub_code)).ToListAsync();
                    }
                }
            }
            else
            {
                if (!string.IsNullOrEmpty(sub_code))
                {
                    list = await _context.MaterialOfTeacher.Include(m => m.Account).Include(m => m.Subject).Where(m => m.SubjectCode.Contains(sub_code)).ToListAsync();
                }
            }
            return View(list);
        }

        // GET: ADMINMaterialOfTeacher/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.MaterialOfTeacher == null)
            {
                return NotFound();
            }

            var materialOfTeacher = await _context.MaterialOfTeacher.FindAsync(id);
            if (materialOfTeacher == null)
            {
                return NotFound();
            }
            materialOfTeacher.Status = "approved";
            _context.Update(materialOfTeacher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: ADMINMaterialOfTeacher/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.MaterialOfTeacher == null)
            {
                return NotFound();
            }

            var materialOfTeacher = await _context.MaterialOfTeacher
                .Include(m => m.Account)
                .Include(m => m.Subject)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (materialOfTeacher == null)
            {
                return NotFound();
            }

            return View(materialOfTeacher);
        }

        // POST: ADMINMaterialOfTeacher/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.MaterialOfTeacher == null)
            {
                return Problem("Entity set 'AppDbContext.MaterialOfTeacher'  is null.");
            }
            var materialOfTeacher = await _context.MaterialOfTeacher.FindAsync(id);
            if (materialOfTeacher != null)
            {
                _context.MaterialOfTeacher.Remove(materialOfTeacher);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MaterialOfTeacherExists(int id)
        {
          return (_context.MaterialOfTeacher?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Lab2_SWT/Views/ADMINMaterialOfTeacher/Create.cshtml
@model LMMProject.Models.MaterialOfTeacher

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>MaterialOfTeacher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TeacherUsername" class="control-label"></label>
                <select asp-for="TeacherUsername" class ="form-control" asp-items="ViewBag.TeacherUsername"></select>
            </div>
            <div class="form-group">
                <label asp-for="SubjectCode" class="control-label"></label>
                <select asp-for="SubjectCode" class ="form-control" asp-items="ViewBag.SubjectCode"></select>
            </div>
            <div class="form-group">
                <label asp-for="URL" class="control-label"></label>
                <input asp-for="URL" class="form-control" />
                <span asp-validation-for="URL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

Lab2_SWT/Views/ADMINMaterialOfTeacher/Delete.cshtml
@model LMMProject.Models.MaterialOfTeacher

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/delete-detail.css">
    <title>Delete</title>
</head>
<body>
    <div class="color">
        <h1> Delete Materials</h1>
    </div>
    <div>
        <div class="container-center">
            <table class="table-1">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Account)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Subject)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.URL)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayFor(model => model.Description)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Account.UserName)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Subject.SubjectCode)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.URL)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Status)
                    </td>
                </tr>
            </table>
            <div class="delete-section">
                <h4>Are you sure you want to delete?</h4>
                <form asp-action="Delete">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="Delete" class="btn btn-danger" class="btn btn-primary" /> |
                    <a asp-action="Index" class="btn btn-primary">Back to List</a>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

Lab2_SWT/Views/ADMINMaterialOfTeacher/Details.cshtml
@model LMMProject.Models.MaterialOfTeacher

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>MaterialOfTeacher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Account)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Account.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.SubjectCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.URL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.URL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

Lab2_SWT/Views/ADMINMaterialOfTeacher/Edit.cshtml
@model LMMProject.Models.MaterialOfTeacher

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>MaterialOfTeacher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TeacherUsername" class="control-label"></label>
                <select asp-for="TeacherUsername" class="form-control" asp-items="ViewBag.TeacherUsername"></select>
                <span asp-validation-for="TeacherUsername" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubjectCode" class="control-label"></label>
                <select asp-for="SubjectCode" class="form-control" asp-items="ViewBag.SubjectCode"></select>
                <span asp-validation-for="SubjectCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="URL" class="control-label"></label>
                <input asp-for="URL" class="form-control" />
                <span asp-validation-for="URL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

Lab2_SWT/Views/ADMINMaterialOfTeacher/Index.cshtml
@model IEnumerable<LMMProject.Models.MaterialOfTeacher>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/curri-listing.css">
</head>
<body>
    <div class="curri-details">
        <div class="navbar">
            <img src="~/image/istockphoto-1138089745-170667a.jpg" class="logo">
            <ul>
                <li><a asp-controller="ADMIN" asp-action="Dashboard">Home</a></li>
            </ul>
        </div>
        <div class="content">
            <b>
                <h1>Learning Materials Management</h1>
                <p>Teacher's materials Listing</p>
            </b>
        </div>



        
        <table class="table table-bordered table-hover">
            <thead class="thead-dark">
                <tr>
                    <td colspan="6">
                        <div class="form-container">
                            <form asp-action="Index" method="get">
                                <select name="status" id="lang-select">
                                    <option value="">--Choose status--</option>
                                    <option value="all">ALL</option>
                                    <option value="approved">APPROVED</option>
                                    <option value="waiting">WAITING</option>
                                </select>                              
                                <label>--Enter subject code:</label>
                                <input name="sub_code" type="text" />
                                <br />
                                <button type="submit" class="btn btn-primary">Filter</button>
                            </form>
                        </div>
                    </td>
                </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                Teacher Name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subject)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.URL)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Account.UserName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Subject.SubjectCode)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.URL)
                            </td>
                            @{
                                if (item.Status.Equals("approved"))
                                {
                                    <td >
                                        <b style="color:green"> @Html.DisplayFor(modelItem => item.Status)</b>
                                    </td>
                                }
                                else
                                {
                                    <td>
                                        <b style="color:orange"> @Html.DisplayFor(modelItem => item.Status)</b>
                                    </td>
                                }
                            }
                            <td>
                                @{
                                    if (!item.Status.Equals("approved"))
                                    {
                                        <p> <a asp-action="Edit" asp-route-id="@item.Id">Allow</a> | </p>
                                    }
                                }

                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-primary">Delete</a>
                            </td>
                        </tr>
                    }
            </tbody>
</table>
        @if (Model.Count() == 0)
        {
            <h2><b>Not found !</b></h2>
        }
    </div>
</body>
</html>